version: '3.7'

services: 
    identity_service:
        build: .
        container_name: identity_app
        environment:
            - ASPNETCORE_URLS=http://*:80
            - ASPNETCORE_ENVIRONMENT=Development
        ports: 
            - "18766:80"
        depends_on: 
            - identity_sqldb
        networks: 
            - identity_network

    identity_sqldb:
        container_name: identity_sql_db
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - "SA_PASSWORD=Pass@word"
            - "ACCEPT_EULA=Y"
        networks: 
            - identity_network

networks:
    identity_network:
        name: identity_network
        driver: bridge